[package]
name = "stash"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stash"
path = "src/main.rs"

[dependencies]
anyhow = "1"
reedline = { git = "https://github.com/nushell/reedline", branch = "main" }
